theme: jekyll-theme-cayman
title: [Drop Icons]
description: [(.ico)]
show_downloads: true

github:
  zip_url: https://github.com/genesistoxical/drop-icons/releases/latest/download/Drop-Icons.zip
  tar_url: https://github.com/genesistoxical/drop-icons/releases/latest/download/Drop-Icons-Installer.exe
  is_project_page: false
