theme: jekyll-theme-modernist
title: Q'zero Cursor
description: Black cursor with white border and danger style details for Windows.
show_downloads: true

github:
  zip_url: https://github.com/genesistoxical/drop-icons/releases/download/1.0.0/Drop-Icons.zip
  is_project_page: true
