theme: jekyll-theme-cayman
title: [Crystal Folders]
show_downloads: true

github:
  zip_url: https://github.com/genesistoxical/drop-icons/releases/latest/download/Crystal-Folders.zip
  tar_url: https://github.com/genesistoxical/drop-icons/releases/latest/download/Crystal-Folders-Installer.exe
  is_project_page: false
