theme: jekyll-theme-modernist
title: Pixie Folders
description: Set of six minimalist and editable folder icon designs.
show_downloads: true

github:
  zip_url: https://github.com/genesistoxical/qzero-cursor/releases/download/1.0/Qzero-Cursor.zip
  is_project_page: true
